site_name: FalloutX Notes

pages:
- Home: index.md
- Notes:
  - 'Elixir Getting Started': notes/elixir_getting_started.md
  - 'Progressive Web Apps': notes/pwa_notes.md
  - 'Data Visualization': notes/datavis_notes.md
  - 'Redux': notes/redux_notes.md
  - Ruby:
    - 'Ruby Notes P1 - CodeAcademy': notes/ruby/ruby_part_1_codeacademy.md
    - 'Ruby Notes P2 - Explantions': notes/ruby/ruby_part_2_explanations.md
    - 'Ruby Notes P3 - Ruby Monk': notes/ruby/ruby_part_3_ruby_monk_intro.md
    - 'Ruby Notes P4 - Ruby Monk Primer Ascent': notes/ruby/ruby_part_4.md
- Resources:
  - 'Learning Ruby': resources/learning_ruby.md
  - 'General Dev Resources': resources/general_dev_resources.md

- __ruby_notes_index: notes/ruby/index.md

- __Internal: internal.md

theme_dir: journal_theme
extra_css: [app.css]
markdown_extensions:
  - pymdownx.tasklist
  - pymdownx.githubemoji
  - pymdownx.superfences
  - pymdownx.betterem
  - pymdownx.tilde
  - pymdownx.magiclink
  - pymdownx.headeranchor
  - pymdownx.progressbar
